// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/comments.yaml
import { z } from 'zod';
import type { ModelRegistration } from '@rhino-dev/rhino-nestjs';

import { CommentPolicy } from '../policies/CommentPolicy';

// ---------------------------------------------------------------------------
// Validation schemas per role
// ---------------------------------------------------------------------------

const validationStore: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    body: z.string(),
    taskId: z.number().int(),
  }),
  admin: z.object({
    body: z.string(),
    taskId: z.number().int(),
  }),
  manager: z.object({
    body: z.string(),
    taskId: z.number().int(),
  }),
  member: z.object({
    body: z.string(),
    taskId: z.number().int(),
  }),
  viewer: z.object({}),
};

const validationUpdate: Record<string, z.ZodTypeAny> = {
  owner: z.object({
    body: z.string().optional(),
  }),
  admin: z.object({
    body: z.string().optional(),
  }),
  manager: z.object({
    body: z.string().optional(),
  }),
  member: z.object({
    body: z.string().optional(),
  }),
  viewer: z.object({}),
};

// ---------------------------------------------------------------------------
// ModelRegistration
// ---------------------------------------------------------------------------

export const commentsRegistration: ModelRegistration = {
  model: 'Comment',
  policy: CommentPolicy,
  validationStore,
  validationUpdate,
  belongsToOrganization: false,
  softDeletes: true,
  hasAuditTrail: false,
  hasUuid: true,
  owner: "task.project",
  fkConstraints: [{"field":"taskId","model":"task"},{"field":"userId","model":"user"}],
};
