<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

/**
 * Seeds roles from Rhino Blueprint definitions.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify _roles.yaml and run: php artisan rhino:blueprint
 */
class RoleSeeder extends Seeder
{
    public function run(): void
    {
        Role::firstOrCreate(
            ['slug' => 'owner'],
            [
                'name' => 'Owner',
                'description' => 'Full access to everything. Manages billing and users.',
            ]
        );
        Role::firstOrCreate(
            ['slug' => 'admin'],
            [
                'name' => 'Admin',
                'description' => 'Operational admin. Full CRUD on all resources.',
            ]
        );
        Role::firstOrCreate(
            ['slug' => 'manager'],
            [
                'name' => 'Manager',
                'description' => 'Can manage projects and tasks, limited field access.',
            ]
        );
        Role::firstOrCreate(
            ['slug' => 'member'],
            [
                'name' => 'Member',
                'description' => 'Can view and work on assigned tasks.',
            ]
        );
        Role::firstOrCreate(
            ['slug' => 'viewer'],
            [
                'name' => 'Viewer',
                'description' => 'Read-only access to projects and tasks.',
            ]
        );
    }
}
