<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\Role;
use App\Models\User;
use App\Models\UserRole;
use Illuminate\Database\Seeder;

/**
 * Seeds sample users with role-based permissions from Rhino Blueprint definitions.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify blueprint files and run: php artisan rhino:blueprint
 */
class UserRoleSeeder extends Seeder
{
    public function run(): void
    {
        $org = Organization::firstOrCreate(
            ['slug' => 'demo-org'],
            [
                'name' => 'Demo Organization',
                'description' => 'Default organization for development',
                'is_active' => true,
            ]
        );

        // Owner
        $ownerUser = User::factory()->create([
            'name' => 'Owner User',
            'email' => 'owner@example.com',
        ]);
        $ownerRole = Role::where('slug', 'owner')->firstOrFail();
        UserRole::firstOrCreate(
            ['user_id' => $ownerUser->id, 'role_id' => $ownerRole->id, 'organization_id' => $org->id],
            ['permissions' => ['*']]
        );
        // Admin
        $adminUser = User::factory()->create([
            'name' => 'Admin User',
            'email' => 'admin@example.com',
        ]);
        $adminRole = Role::where('slug', 'admin')->firstOrFail();
        UserRole::firstOrCreate(
            ['user_id' => $adminUser->id, 'role_id' => $adminRole->id, 'organization_id' => $org->id],
            ['permissions' => [
                'comments.destroy',
                'comments.index',
                'comments.restore',
                'comments.show',
                'comments.store',
                'comments.trashed',
                'comments.update',
                'labels.destroy',
                'labels.index',
                'labels.restore',
                'labels.show',
                'labels.store',
                'labels.trashed',
                'labels.update',
                'projects.destroy',
                'projects.index',
                'projects.restore',
                'projects.show',
                'projects.store',
                'projects.trashed',
                'projects.update',
                'tasks.destroy',
                'tasks.index',
                'tasks.restore',
                'tasks.show',
                'tasks.store',
                'tasks.trashed',
                'tasks.update',
            ]]
        );
        // Manager
        $managerUser = User::factory()->create([
            'name' => 'Manager User',
            'email' => 'manager@example.com',
        ]);
        $managerRole = Role::where('slug', 'manager')->firstOrFail();
        UserRole::firstOrCreate(
            ['user_id' => $managerUser->id, 'role_id' => $managerRole->id, 'organization_id' => $org->id],
            ['permissions' => [
                'comments.destroy',
                'comments.index',
                'comments.show',
                'comments.store',
                'comments.update',
                'labels.index',
                'labels.show',
                'labels.store',
                'labels.update',
                'projects.index',
                'projects.show',
                'projects.store',
                'projects.update',
                'tasks.index',
                'tasks.show',
                'tasks.store',
                'tasks.update',
            ]]
        );
        // Member
        $memberUser = User::factory()->create([
            'name' => 'Member User',
            'email' => 'member@example.com',
        ]);
        $memberRole = Role::where('slug', 'member')->firstOrFail();
        UserRole::firstOrCreate(
            ['user_id' => $memberUser->id, 'role_id' => $memberRole->id, 'organization_id' => $org->id],
            ['permissions' => [
                'comments.index',
                'comments.show',
                'comments.store',
                'comments.update',
                'labels.index',
                'labels.show',
                'projects.index',
                'projects.show',
                'tasks.index',
                'tasks.show',
                'tasks.update',
            ]]
        );
        // Viewer
        $viewerUser = User::factory()->create([
            'name' => 'Viewer User',
            'email' => 'viewer@example.com',
        ]);
        $viewerRole = Role::where('slug', 'viewer')->firstOrFail();
        UserRole::firstOrCreate(
            ['user_id' => $viewerUser->id, 'role_id' => $viewerRole->id, 'organization_id' => $org->id],
            ['permissions' => [
                'comments.index',
                'comments.show',
                'labels.index',
                'labels.show',
                'projects.index',
                'projects.show',
                'tasks.index',
                'tasks.show',
            ]]
        );
    }
}
