// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/projects.yaml
import { ResourcePolicy } from '@rhino-dev/rhino-nestjs';

/**
 * Authorization policy for the Project resource.
 * Regenerate with: npx rhino blueprint
 */
export class ProjectPolicy extends ResourcePolicy {
  override resourceSlug = 'projects';

  override permittedAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org)) {
      return ['*'];
    }
    if (this.hasRole(user, 'manager', org)) {
      return ['id', 'title', 'description', 'status', 'budget', 'startsAt', 'endsAt'];
    }
    if (this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      return ['id', 'title', 'description', 'status', 'startsAt', 'endsAt'];
    }
    return [];
  }

  override hiddenAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'manager', org)) {
      return ['internalNotes'];
    }
    if (this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      return ['budget', 'internalNotes'];
    }
    return [];
  }

  override permittedAttributesForCreate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org)) {
      return ['title', 'description', 'status', 'budget', 'internalNotes', 'startsAt', 'endsAt'];
    }
    if (this.hasRole(user, 'manager', org)) {
      return ['title', 'description', 'status', 'startsAt', 'endsAt'];
    }
    return [];
  }

  override permittedAttributesForUpdate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org)) {
      return ['title', 'description', 'status', 'budget', 'internalNotes', 'startsAt', 'endsAt'];
    }
    if (this.hasRole(user, 'manager', org)) {
      return ['title', 'description', 'status', 'startsAt', 'endsAt'];
    }
    return [];
  }
}
