// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/tasks.yaml
import { ResourcePolicy } from '@rhino-dev/rhino-nestjs';

/**
 * Authorization policy for the Task resource.
 * Regenerate with: npx rhino blueprint
 */
export class TaskPolicy extends ResourcePolicy {
  override resourceSlug = 'tasks';

  override permittedAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['*'];
    }
    if (this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      return ['id', 'title', 'description', 'status', 'priority', 'dueDate', 'projectId', 'assignedTo'];
    }
    return [];
  }

  override hiddenAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      return ['estimatedHours'];
    }
    return [];
  }

  override permittedAttributesForCreate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['title', 'description', 'status', 'priority', 'estimatedHours', 'dueDate', 'projectId', 'assignedTo'];
    }
    return [];
  }

  override permittedAttributesForUpdate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['title', 'description', 'status', 'priority', 'estimatedHours', 'dueDate', 'projectId', 'assignedTo'];
    }
    if (this.hasRole(user, 'member', org)) {
      return ['status', 'description'];
    }
    return [];
  }
}
