// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/tasks.yaml
import { ResourcePolicy } from '@rhino-dev/rhino-nestjs';

/**
 * Authorization policy for the Task resource.
 * Regenerate with: npx rhino blueprint
 */
export class TaskPolicy extends ResourcePolicy {
  override resourceSlug = 'tasks';

  override permittedAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['*'];
    }
    if (this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      // Computed attributes go through this same gate. Junior roles may ask
      // for the windowed counts but not the money-adjacent or per-status
      // breakdowns (see hiddenAttributesForShow).
      return ['id', 'title', 'description', 'status', 'priority', 'dueDate', 'projectId', 'assignedTo',
        'isOverdue', 'isDueBefore',
        'totalCount', 'openTasksCount', 'doneTasksCount', 'highPriorityCount',
        'tasksDueBetween', 'countByStatus', 'windowedTaskCount'];
    }
    return [];
  }

  override hiddenAttributesForShow(user: any, org?: any): string[] {
    if (this.hasRole(user, 'member', org) ||
      this.hasRole(user, 'viewer', org)) {
      // The blacklist beats the whitelist: 'countByStatus' is listed above and
      // still denied here. A denied computed attribute reports the same
      // "is not allowed" message an undeclared one does, and that check runs
      // BEFORE any argument binding — so a junior role cannot learn an
      // attribute exists by probing its parameters.
      return ['estimatedHours', 'countByStatus'];
    }
    return [];
  }

  /**
   * Named scopes each role may select with ?scope=. Everyone can list their own
   * work; the date-window scopes are for the roles that plan schedules.
   */
  override permittedScopes(user: any, org?: any): string[] {
    if (
      this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)
    ) {
      return ['*'];
    }
    return ['assignedToMe', 'byStatus'];
  }

  override permittedAttributesForCreate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['title', 'description', 'status', 'priority', 'estimatedHours', 'dueDate', 'projectId', 'assignedTo'];
    }
    return [];
  }

  override permittedAttributesForUpdate(user: any, org?: any): string[] {
    if (this.hasRole(user, 'owner', org) ||
      this.hasRole(user, 'admin', org) ||
      this.hasRole(user, 'manager', org)) {
      return ['title', 'description', 'status', 'priority', 'estimatedHours', 'dueDate', 'projectId', 'assignedTo'];
    }
    if (this.hasRole(user, 'member', org)) {
      return ['status', 'description'];
    }
    return [];
  }
}
