<?php

namespace App\Policies;

use App\Models\Task;
use Rhino\Policies\ResourcePolicy;
use Illuminate\Contracts\Auth\Authenticatable;

/**
 * Policy for the Task resource.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify the blueprint YAML and run: php artisan rhino:blueprint
 */
class TaskPolicy extends ResourcePolicy
{
    // ---------------------------------------------------------------
    // Attribute Permissions (generated from blueprint)
    // ---------------------------------------------------------------

    public function permittedAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return ['*'];
        }

        if ($this->hasRole($user, 'member') || $this->hasRole($user, 'viewer')) {
            return [
                'id',
                'title',
                'description',
                'status',
                'priority',
                'due_date',
                'project_id',
                'assignee_id',
            ];
        }

        return [];
    }

    public function hiddenAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'member') || $this->hasRole($user, 'viewer')) {
            return ['estimated_hours'];
        }

        return [];
    }

    public function permittedAttributesForCreate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return [
                'title',
                'description',
                'status',
                'priority',
                'estimated_hours',
                'due_date',
                'project_id',
                'assignee_id',
            ];
        }

        return [];
    }

    public function permittedAttributesForUpdate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return [
                'title',
                'description',
                'status',
                'priority',
                'estimated_hours',
                'due_date',
                'project_id',
                'assignee_id',
            ];
        }

        if ($this->hasRole($user, 'member')) {
            return ['status', 'description'];
        }

        return [];
    }
}
