<?php

namespace App\Policies;

use App\Models\Project;
use Rhino\Policies\ResourcePolicy;
use Illuminate\Contracts\Auth\Authenticatable;

/**
 * Policy for the Project resource.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify the blueprint YAML and run: php artisan rhino:blueprint
 */
class ProjectPolicy extends ResourcePolicy
{
    // ---------------------------------------------------------------
    // Attribute Permissions (generated from blueprint)
    // ---------------------------------------------------------------

    public function permittedAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner') || $this->hasRole($user, 'admin')) {
            return ['*'];
        }

        if ($this->hasRole($user, 'manager')) {
            return ['id', 'title', 'description', 'status', 'budget', 'starts_at', 'ends_at'];
        }

        if ($this->hasRole($user, 'member') || $this->hasRole($user, 'viewer')) {
            return ['id', 'title', 'description', 'status', 'starts_at', 'ends_at'];
        }

        return [];
    }

    public function hiddenAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'manager')) {
            return ['internal_notes'];
        }

        if ($this->hasRole($user, 'member') || $this->hasRole($user, 'viewer')) {
            return ['budget', 'internal_notes'];
        }

        return [];
    }

    public function permittedAttributesForCreate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner') || $this->hasRole($user, 'admin')) {
            return [
                'title',
                'description',
                'status',
                'budget',
                'internal_notes',
                'starts_at',
                'ends_at',
            ];
        }

        if ($this->hasRole($user, 'manager')) {
            return ['title', 'description', 'status', 'starts_at', 'ends_at'];
        }

        return [];
    }

    public function permittedAttributesForUpdate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner') || $this->hasRole($user, 'admin')) {
            return [
                'title',
                'description',
                'status',
                'budget',
                'internal_notes',
                'starts_at',
                'ends_at',
            ];
        }

        if ($this->hasRole($user, 'manager')) {
            return ['title', 'description', 'status', 'starts_at', 'ends_at'];
        }

        return [];
    }
}
