<?php

namespace App\Policies;

use App\Models\Task;
use Rhino\Policies\ResourcePolicy;
use Illuminate\Contracts\Auth\Authenticatable;

/**
 * Policy for the Task resource.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify the blueprint YAML and run: php artisan rhino:blueprint
 */
class TaskPolicy extends ResourcePolicy
{
    // ---------------------------------------------------------------
    // Attribute Permissions (generated from blueprint)
    // ---------------------------------------------------------------

    public function permittedAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return ['*'];
        }

        if ($this->hasRole($user, 'member') || $this->hasRole($user, 'viewer')) {
            return [
                'id',
                'title',
                'description',
                'status',
                'priority',
                'due_date',
                'project_id',
                'assignee_id',
                // Computed attributes go through this same gate. Junior roles
                // may ask for the windowed counts but not the money-adjacent
                // or per-status breakdowns (see hiddenAttributesForShow).
                'comment_count',
                'is_overdue',
                'is_due_before',
                'total_count',
                'open_tasks_count',
                'done_tasks_count',
                'high_priority_count',
                'tasks_due_between',
                'count_by_status',
                'windowed_task_count',
            ];
        }

        return [];
    }

    public function hiddenAttributesForShow(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'member') || $this->hasRole($user, 'viewer')) {
            // The blacklist beats the whitelist: 'count_by_status' is listed
            // above and still denied here. A denied computed attribute reports
            // the same "is not allowed" message an undeclared one does, and
            // that check runs BEFORE any argument binding — so a junior role
            // cannot learn an attribute exists by probing its parameters.
            return ['estimated_hours', 'count_by_status'];
        }

        return [];
    }

    /**
     * Named scopes each role may select with ?scope=.
     *
     * Everyone can list their own work; the date-window scopes are for the
     * roles that plan schedules.
     */
    public function permittedScopes(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner') || $this->hasRole($user, 'admin') || $this->hasRole($user, 'manager')) {
            return ['*'];
        }

        return ['assignedToMe', 'byStatus'];
    }

    public function permittedAttributesForCreate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return [
                'title',
                'description',
                'status',
                'priority',
                'estimated_hours',
                'due_date',
                'project_id',
                'assignee_id',
            ];
        }

        return [];
    }

    public function permittedAttributesForUpdate(?\Illuminate\Contracts\Auth\Authenticatable $user): array
    {
        if ($this->hasRole($user, 'owner')
            || $this->hasRole($user, 'admin')
            || $this->hasRole($user, 'manager')) {
            return [
                'title',
                'description',
                'status',
                'priority',
                'estimated_hours',
                'due_date',
                'project_id',
                'assignee_id',
            ];
        }

        if ($this->hasRole($user, 'member')) {
            return ['status', 'description'];
        }

        return [];
    }
}
