// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/comments.yaml
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed sample Comment rows.
 * Run: npx ts-node src/seeders/CommentSeeder.ts
 */
export async function seed(): Promise<void> {
  console.log('Seeding Comment...');

  await prisma.comment.upsert({
    where: { id: '00000000-0000-0000-0000-000000000001' },
    update: {},
    create: {
      id: "00000000-0000-0000-0000-000000000001",
      body: "Sample Body content for row 1.",
      taskId: 1,
      userId: 1,
    },
  });

  await prisma.comment.upsert({
    where: { id: '00000000-0000-0000-0000-000000000002' },
    update: {},
    create: {
      id: "00000000-0000-0000-0000-000000000002",
      body: "Sample Body content for row 2.",
      taskId: 1,
      userId: 1,
    },
  });

  await prisma.comment.upsert({
    where: { id: '00000000-0000-0000-0000-000000000003' },
    update: {},
    create: {
      id: "00000000-0000-0000-0000-000000000003",
      body: "Sample Body content for row 3.",
      taskId: 1,
      userId: 1,
    },
  });

  console.log('✓ Comment seeded (3 rows)');
}

// Allow running directly
if (require.main === module) {
  seed()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
