// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/labels.yaml
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed sample Label rows.
 * Run: npx ts-node src/seeders/LabelSeeder.ts
 */
export async function seed(): Promise<void> {
  console.log('Seeding Label...');

  await prisma.label.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      organizationId: 1,
      name: "Sample Name 1",
      color: "Sample Color 1",
    },
  });

  await prisma.label.upsert({
    where: { id: 2 },
    update: {},
    create: {
      id: 2,
      organizationId: 1,
      name: "Sample Name 2",
      color: "Sample Color 2",
    },
  });

  await prisma.label.upsert({
    where: { id: 3 },
    update: {},
    create: {
      id: 3,
      organizationId: 1,
      name: "Sample Name 3",
      color: "Sample Color 3",
    },
  });

  console.log('✓ Label seeded (3 rows)');
}

// Allow running directly
if (require.main === module) {
  seed()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
