// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/projects.yaml
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed sample Project rows.
 * Run: npx ts-node src/seeders/ProjectSeeder.ts
 */
export async function seed(): Promise<void> {
  console.log('Seeding Project...');

  await prisma.project.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      organizationId: 1,
      title: "Sample Title 1",
      description: "Sample Description content for row 1.",
      status: "draft",
      budget: 9.99,
      internalNotes: "Sample InternalNotes content for row 1.",
      startsAt: "2024-01-01T00:00:00.000Z",
      endsAt: "2024-01-01T00:00:00.000Z",
    },
  });

  await prisma.project.upsert({
    where: { id: 2 },
    update: {},
    create: {
      id: 2,
      organizationId: 1,
      title: "Sample Title 2",
      description: "Sample Description content for row 2.",
      status: "draft",
      budget: 19.98,
      internalNotes: "Sample InternalNotes content for row 2.",
      startsAt: "2024-02-01T00:00:00.000Z",
      endsAt: "2024-02-01T00:00:00.000Z",
    },
  });

  await prisma.project.upsert({
    where: { id: 3 },
    update: {},
    create: {
      id: 3,
      organizationId: 1,
      title: "Sample Title 3",
      description: "Sample Description content for row 3.",
      status: "draft",
      budget: 29.97,
      internalNotes: "Sample InternalNotes content for row 3.",
      startsAt: "2024-03-01T00:00:00.000Z",
      endsAt: "2024-03-01T00:00:00.000Z",
    },
  });

  console.log('✓ Project seeded (3 rows)');
}

// Allow running directly
if (require.main === module) {
  seed()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
