// Generated by Rhino Blueprint — do not edit directly.
// Source: .rhino/blueprints/tasks.yaml
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed sample Task rows.
 * Run: npx ts-node src/seeders/TaskSeeder.ts
 */
export async function seed(): Promise<void> {
  console.log('Seeding Task...');

  await prisma.task.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      title: "Sample Title 1",
      description: "Sample Description content for row 1.",
      status: "todo",
      priority: "medium",
      estimatedHours: 9.99,
      dueDate: "2024-01-01T00:00:00.000Z",
      projectId: 1,
      assignedTo: 1,
    },
  });

  await prisma.task.upsert({
    where: { id: 2 },
    update: {},
    create: {
      id: 2,
      title: "Sample Title 2",
      description: "Sample Description content for row 2.",
      status: "todo",
      priority: "medium",
      estimatedHours: 19.98,
      dueDate: "2024-02-01T00:00:00.000Z",
      projectId: 1,
      assignedTo: 1,
    },
  });

  await prisma.task.upsert({
    where: { id: 3 },
    update: {},
    create: {
      id: 3,
      title: "Sample Title 3",
      description: "Sample Description content for row 3.",
      status: "todo",
      priority: "medium",
      estimatedHours: 29.97,
      dueDate: "2024-03-01T00:00:00.000Z",
      projectId: 1,
      assignedTo: 1,
    },
  });

  console.log('✓ Task seeded (3 rows)');
}

// Allow running directly
if (require.main === module) {
  seed()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
