/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Organization: {
            id?: number;
            name?: string;
            slug?: string;
            domain?: string | null;
            description?: string | null;
            is_active?: number;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        Role: {
            id?: number;
            name?: string;
            slug?: string;
            description?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        User: {
            id?: number;
            name?: string;
            email?: string;
            /** Format: date-time */
            email_verified_at?: string | null;
            password?: string;
            remember_token?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        UserRole: {
            id?: number;
            user_id?: number;
            role_id?: number;
            organization_id?: number;
            permissions?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Comment: {
            id?: number;
            uuid?: string;
            body?: string;
            task_id?: number;
            user_id?: number;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Label: {
            id?: number;
            organization_id?: number;
            name?: string;
            color?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Project: {
            id?: number;
            organization_id?: number;
            title?: string;
            description?: string | null;
            status?: string;
            budget?: number | null;
            internal_notes?: string | null;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Task: {
            id?: number;
            title?: string;
            description?: string | null;
            status?: string;
            priority?: string;
            estimated_hours?: number | null;
            /** Format: date-time */
            due_date?: string | null;
            project_id?: number;
            assignee_id?: number | null;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
